# Generated by Django 3.2 on 2021-06-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_id_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_card',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
